/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/post": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.post.id"];
          name?: parameters["rowFilter.post.name"];
          description?: parameters["rowFilter.post.description"];
          images?: parameters["rowFilter.post.images"];
          pet_status?: parameters["rowFilter.post.pet_status"];
          location?: parameters["rowFilter.post.location"];
          posted_by?: parameters["rowFilter.post.posted_by"];
          created_at?: parameters["rowFilter.post.created_at"];
          updated_at?: parameters["rowFilter.post.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["post"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** post */
          post?: definitions["post"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.post.id"];
          name?: parameters["rowFilter.post.name"];
          description?: parameters["rowFilter.post.description"];
          images?: parameters["rowFilter.post.images"];
          pet_status?: parameters["rowFilter.post.pet_status"];
          location?: parameters["rowFilter.post.location"];
          posted_by?: parameters["rowFilter.post.posted_by"];
          created_at?: parameters["rowFilter.post.created_at"];
          updated_at?: parameters["rowFilter.post.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.post.id"];
          name?: parameters["rowFilter.post.name"];
          description?: parameters["rowFilter.post.description"];
          images?: parameters["rowFilter.post.images"];
          pet_status?: parameters["rowFilter.post.pet_status"];
          location?: parameters["rowFilter.post.location"];
          posted_by?: parameters["rowFilter.post.posted_by"];
          created_at?: parameters["rowFilter.post.created_at"];
          updated_at?: parameters["rowFilter.post.updated_at"];
        };
        body: {
          /** post */
          post?: definitions["post"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          name?: parameters["rowFilter.profile.name"];
          created_at?: parameters["rowFilter.profile.created_at"];
          user_id?: parameters["rowFilter.profile.user_id"];
          email?: parameters["rowFilter.profile.email"];
          phone_number?: parameters["rowFilter.profile.phone_number"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          name?: parameters["rowFilter.profile.name"];
          created_at?: parameters["rowFilter.profile.created_at"];
          user_id?: parameters["rowFilter.profile.user_id"];
          email?: parameters["rowFilter.profile.email"];
          phone_number?: parameters["rowFilter.profile.phone_number"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          name?: parameters["rowFilter.profile.name"];
          created_at?: parameters["rowFilter.profile.created_at"];
          user_id?: parameters["rowFilter.profile.user_id"];
          email?: parameters["rowFilter.profile.email"];
          phone_number?: parameters["rowFilter.profile.phone_number"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Information about the missing pet */
  post: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    name: string;
    /** Format: text */
    description: string;
    /** Format: ARRAY */
    images: unknown[];
    /** Format: text */
    pet_status: string;
    /** Format: json */
    location: string;
    /** Format: uuid */
    posted_by?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
  };
  /** @description Extra information about currently registered users */
  profile: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: text */
    name: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: uuid */
    user_id: string;
    /** Format: text */
    email: string;
    /** Format: text */
    phone_number?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description post */
  "body.post": definitions["post"];
  /** Format: bigint */
  "rowFilter.post.id": string;
  /** Format: text */
  "rowFilter.post.name": string;
  /** Format: text */
  "rowFilter.post.description": string;
  /** Format: ARRAY */
  "rowFilter.post.images": string;
  /** Format: text */
  "rowFilter.post.pet_status": string;
  /** Format: json */
  "rowFilter.post.location": string;
  /** Format: uuid */
  "rowFilter.post.posted_by": string;
  /** Format: timestamp with time zone */
  "rowFilter.post.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.post.updated_at": string;
  /** @description profile */
  "body.profile": definitions["profile"];
  /** Format: uuid */
  "rowFilter.profile.id": string;
  /** Format: text */
  "rowFilter.profile.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.profile.created_at": string;
  /** Format: uuid */
  "rowFilter.profile.user_id": string;
  /** Format: text */
  "rowFilter.profile.email": string;
  /** Format: text */
  "rowFilter.profile.phone_number": string;
}

export interface operations {}

export interface external {}
